FROM maven:3.6.0-jdk-11-slim AS build
WORKDIR /home/app
RUN apt-get update -y
RUN apt-get install -y python
COPY . /home/app
RUN mvn -pl site.ycsb:redis-binding -am clean package

ENTRYPOINT ["bin/ycsb"]